# Generated by Django 2.0 on 2018-06-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(db_column='user_name', max_length=20)),
                ('password', models.CharField(db_column='password', max_length=20)),
                ('trueName', models.CharField(db_column='true_name', max_length=20)),
                ('email', models.EmailField(db_column='email', max_length=20)),
                ('phone', models.CharField(db_column='phone', max_length=20)),
                ('isValid', models.IntegerField(db_column='is_valid')),
                ('createDate', models.DateTimeField(db_column='create_date')),
                ('updateDate', models.DateTimeField(db_column='update_date', max_length=20)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
