# Generated by Django 2.0 on 2018-06-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleChance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanceSource', models.CharField(db_column='chance_source', max_length=300)),
                ('customerId', models.IntegerField(db_column='customer_id')),
                ('customerName', models.CharField(db_column='customer_name', max_length=100)),
                ('cgjl', models.IntegerField(db_column='cgjl')),
                ('overview', models.CharField(db_column='overview', max_length=300)),
                ('linkMan', models.CharField(db_column='link_man', max_length=20)),
                ('linkPhone', models.CharField(db_column='link_phone', max_length=20)),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('createMan', models.CharField(db_column='create_man', max_length=20)),
                ('assignMan', models.CharField(db_column='assign_man', max_length=20)),
                ('assignTime', models.DateTimeField(auto_now_add=True, db_column='assign_time')),
                ('state', models.CharField(db_column='state', max_length=20)),
                ('devResult', models.CharField(db_column='dev_result', max_length=20)),
                ('isValid', models.IntegerField(db_column='is_valid')),
                ('createDate', models.DateTimeField(db_column='create_date')),
                ('updateDate', models.DateTimeField(db_column='update_date', max_length=20)),
            ],
            options={
                'db_table': 't_sale_chance',
            },
        ),
    ]
